### ISSUE TITLE
make_file_TMATS.m still tries to build Turbine_NPSS_TMATS.c

### ISSUE THREAD

**Issue by georgelthomas** [nasa/T-MATS#52]
In latest commit as of today (5a448ce), I get a error during install that Turbine_NPSS_TMATS.c cannot be built, as it does not exist. If I've read the old commit messages correctly, this block is no longer used (is lumped in with the regular turbine block).

The commit can be found here: https://github.com/nasa/T-MATS/commit/5a448ce12c836cf375d34860ae8301569d7d07ab

I commented out line 26 in make_file_TMATS.m and install goes ok for me.

**Comment by GRC-RHC-Sim** [comment]
George,  thanks for the comment.  The bug has been fixed. Commit is located at 1ff5fea4b1858fee2f96126567e6e4f1974a2fd9

Thanks,
-Jeff
