### ISSUE TITLE
Cantera Integrated Blocks

### ISSUE THREAD

**Issue by ck1313** [nasa/T-MATS#56]
In FlowDef.m:  
In function obj = set_TsPsMN(obj,Ts,Ps,MN)
line 407: last = -9999;
I think it should be -999.
Because in the function iterSecant(simple secant solver), lastin = -999 when determines if this is first pass to change .05 for initial perturbation.

**Comment by GRC-RHC-Sim** [comment]
Nice catch! Thanks for the heads up.
Updated 12/21/2015, dbae18d5718892bf3ef46964b80e33ea75e52835
