### ISSUE TITLE
Cantera Integrated Blocks_TMATSC_compressor

### ISSUE THREAD

**Issue by ck1313** [nasa/T-MATS#57]
In TMATSC_compressor.m:
line 232: pwr = FI.W * (FI.ht - FO.ht) * 1.4148;
line 233: pwr = pwr + Fbleed1.W*(Fbleed1.ht - FO.ht)*1.4148 + Fbleed2.W*(Fbleed2.ht - FO.ht)*1.4148;
I think it should be pwr = pwr - Fbleed1.W*(Fbleed1.ht - FO.ht)*1.4148 - Fbleed2.W*(Fbleed2.ht - FO.ht)*1.4148;
because of the pwr in line 232, including all flow from the input, which means it calculates the power of bleed. In the 233, the power of bleed should be  cut.

**Comment by GRC-RHC-Sim** [comment]
ck1313,  
Yes, I totally agree.  Thanks so much for finding this bug. Bleed from an earlier stage should reduce the power requirement for the compressor not make it higher.

Updated; 12/21/2015
117f95867ee13745ac7032c4f127f48a5c94aeea

-Jeff
