### ISSUE TITLE
Seg-V issues isolated for 3 blocks

### ISSUE THREAD

**Issue by phasemargin** [nasa/T-MATS#66]
T-MATS is an impressive tool.  However, we experienced some Seg-V's while running the example "GasTurbine_Dyn_Template" on linux.  A code inspection found a few issues where the IWork vector was being accessed beyond its length in 3 files.  Other S-functions may also have the same issue, but are not exercised by "GasTurbine_Dyn_Template".

One recommendation is to mistake-proof the S-function work vectors for future maintenance actions, by naming each element in a C enumeration instead of using a raw integer (see example below). 

BUG ISOLATION: Here is my colleague's analysis and diffs between the repaired code and the tip of the trunk (output of diff was altered since GitHub interprets the - and + from diff as bullets):

-----------------
Good news. After seeing the stack trace:

[  4] 0x00007f1518f1cd1a free at
/mathworks/devel/bat/Bmain_PP/build/matlab/tools/memory/diagnostic_framework/src/mmi/mmi.cpp:683
(in /local-ssd/auser/mds/matlab/bin/glnxa64/libmwmmi.so)
[  5] 0x00007f14d357e287 slModel::shutdownModel() at
/local-ssd/auser/mds/matlab/src/simulink/sl_engin/model.cpp:1570 (in
/local-ssd/auser/mds/matlab/bin/glnxa64/libmwsimulink.so)

and the line model.cpp:1570

    /* Free Work Vectors Array */
    utFree(dataVectors.dWork);

I decided to check c-code before loading gdb. I suspected work vectors,
and found that a number of IWork vectors have not been sized properly.

% diff -uN tmp MEX
diff -uN tmp/Ambient_TMATS.c MEX/Ambient_TMATS.c

Current:    ssSetNumIWork(S, 2);
Corrected:    ssSetNumIWork(S, 5);

diff -uN tmp/Mixer_TMATS.c MEX/Mixer_TMATS.c

Current: ssSetNumIWork(S, 8);
Corrected: ssSetNumIWork(S, 18);

diff -uN tmp/Nozzle_TMATS.c MEX/Nozzle_TMATS.c
Current:   ssSetNumIWork(S, 11);
Corrected: ssSetNumIWork(S, 14);

---------------------
BUG PREVENTION:  One convention (there are several others) that can help with bitfield and arrays-as-structs uses of data is to employ an enumeration to manage the elements like this:

typedef enum { FIRST_ITEM=0, ANOTHER_ITEM, NUM_IWORK } IWorkIdx;

and then use them like this:

ssSetNumIWork( S, NUM_IWORK );
[...]
ssSetIWorkValue(S, FIRST_ITEM, 0);
ssSetIWorkValue(S, ANOTHER_ITEM, 0);

Insert a new item this way:

typedef enum { FIRST_ITEM=0, ANOTHER_ITEM, NEW_ITEM, NUM_IWORK } IWorkIdx;

and use it like this: 

ssSetIWorkValue(S, NEW_ITEM, 0);

The NUM_IWORK value is "automatically" kept up to date and you get the bonus of using names for the elements instead of indices that might need to be updated (less likely to be off by one). The only gotcha left is to ensure NUM_IWORK is always the last item in the enum.

An alternative is to use individual named DWorks instead of a big IWork vector - then it's even possible get the names automatically from MATLAB scripts.

**Comment by GRC-RHC-Sim** [comment]
Hey, thanks for using T-MATS and posting these bugs. 
I  looked over the issue and agree with pretty much everything you stated. Fortunately, the vector was only being used to prevent error spamming, so the bug would not have damaged functionality.

The issue has been fixed in commit
f88dbdcddeb233c25be9dee7066cbf784f04f805
as of 3/21/2016.  The implementation follows the suggestion above and changes the numbers to an enumeration, promoting good coding practices. The updated code builds on PC and MAC and seems to be working well,  if you have any issues with it let me know. 

Thanks, 
Jeff
