### ISSUE TITLE
Test method for operation range

### ISSUE THREAD

**Issue by chengdingding** [nasa/T-MATS#91]
How do I test the running range of the model or can you provide me with the operating parameters of the JT9D engine?
Thank you for your help.

**Comment by chapman178** [comment]
Sorry for my delayed response. I have not actually mapped this engine out much.  To do that I would suggest creating a very slow controller then dynamically driving the model through the envelope. 

For more of a fully functional engine package I would suggest using the AGTF30, it does have a fully mapped out envelope. https://github.com/nasa/AGTF30
